context:
  version: "0.3.2"
  python_min: "3.11"

package:
  name: tdiff
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/tdiff/tdiff-${{ version }}.tar.gz
    sha256: cb533f3cd9047de92e4fe8ff3d17df202a57b22b4a300cb0e1c3c03184630a88

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - tdiff = tdiff.cli:app
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.11.6,<1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - anyio <5,>=4.13.0
    - cyclopts <5,>=4.10.2
    - textual-diff-view <1,>=0.1.4
    - git

tests:
  - python:
      imports:
        - tdiff
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script: tdiff --help

about:
  summary: Textual diff application
  homepage: https://github.com/davidbrochart/tdiff
  repository: https://github.com/davidbrochart/tdiff
  license: AGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - apcamargo
